- name: General Playbook
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Set execution permission to add script env
      file:
        path: "~/movie-analyst-playbooks-scripts/add_env_var.sh"
        mode: "u+x"

    - name: Execute add variables script
      shell: "~/movie-analyst-playbooks-scripts/add_env_var.sh /home/ubuntu/.env"

    - name: Set execution permission to general script
      file:
        path: "~/movie-analyst-playbooks-scripts/general.sh"
        mode: "u+x"

    - name: Execute general script
      shell: "sudo ~/movie-analyst-playbooks-scripts/general.sh"

    - name: Set execution permission to specific script
      become_user: root
      file:
        path: "~/movie-analyst-playbooks-scripts/{{host}}/{{host}}.sh"
        mode: "u+x"

    - name: Execute specific script
      shell: "~/movie-analyst-playbooks-scripts/{{host}}/{{host}}.sh ~/.env"
